steps:
# deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
    - run
    - --filename=cms-deploy.yaml
    - --image=northamerica-northeast1-docker.pkg.dev/nbd-rta-dev-01/paulo-docker-test-repo/paulo:1
    - --location=northamerica-northeast1
    - --cluster=paulo-autopilot