apiVersion: apps/v1
kind: Deployment
metadata:
  name: paulo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      run: paulo-app
  template:
    metadata:
      labels:
        run: paulo-app
    spec:
      containers:
        - name: paulo-app
          image: northamerica-northeast1-docker.pkg.dev/nbd-rta-dev-01/paulo-docker-test-repo/paulo:1